artifact_uri: file:C:/Users/khrib/OneDrive/Bureau/simplon_nicema/flashcards-project/mlflow_tracking/869484762084459009/76672b2a997b4e7ab6e5bafd15b38e4b/artifacts
end_time: 1748424136248
entry_point_name: ''
experiment_id: '869484762084459009'
lifecycle_stage: active
run_id: 76672b2a997b4e7ab6e5bafd15b38e4b
run_name: capable-mole-580
run_uuid: 76672b2a997b4e7ab6e5bafd15b38e4b
source_name: ''
source_type: 4
source_version: ''
start_time: 1748424136098
status: 3
tags: []
user_id: khrib
