artifact_location: file:C:/Users/khrib/OneDrive/Bureau/simplon_nicema/flashcards-project/mlflow_tracking/869484762084459009
creation_time: 1748424123899
experiment_id: '869484762084459009'
last_update_time: 1748424123899
lifecycle_stage: active
name: llm_service_tracking
