artifact_uri: file:C:/Users/khrib/OneDrive/Bureau/simplon_nicema/flashcards-project/mlflow_tracking/869484762084459009/959f77be3c7d42d6acaa8a94d77c81f1/artifacts
end_time: 1748424136452
entry_point_name: ''
experiment_id: '869484762084459009'
lifecycle_stage: active
run_id: 959f77be3c7d42d6acaa8a94d77c81f1
run_name: nebulous-fox-548
run_uuid: 959f77be3c7d42d6acaa8a94d77c81f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1748424136260
status: 3
tags: []
user_id: khrib
