global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend Service - Main API and business logic
  - job_name: 'backend-service'
    static_configs:
      - targets: ['backend-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # OCR Service - Document text extraction
  - job_name: 'ocr-service'
    static_configs:
      - targets: ['ocr-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # LLM Service - AI flashcard generation
  - job_name: 'llm-service'
    static_configs:
      - targets: ['llm-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Frontend Service - Web interface
  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis - Cache and session storage
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Database Service - SQLite monitoring
  - job_name: 'db-service'
    static_configs:
      - targets: ['db-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # MLflow - ML model tracking (if available)
  - job_name: 'mlflow'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
