artifact_uri: file:C:/Users/khrib/OneDrive/Bureau/simplon_nicema/flashcards-project/mlflow_tracking/869484762084459009/7cad7da5adcb4b7ea6c45551d3c92e67/artifacts
end_time: 1748424136624
entry_point_name: ''
experiment_id: '869484762084459009'
lifecycle_stage: active
run_id: 7cad7da5adcb4b7ea6c45551d3c92e67
run_name: enchanting-hawk-881
run_uuid: 7cad7da5adcb4b7ea6c45551d3c92e67
source_name: ''
source_type: 4
source_version: ''
start_time: 1748424136465
status: 3
tags: []
user_id: khrib
