artifact_uri: file:C:/Users/khrib/OneDrive/Bureau/simplon_nicema/flashcards-project/mlflow_tracking/869484762084459009/fc9989dbb9a9406eb14cb0db7b94ecc3/artifacts
end_time: 1748424136814
entry_point_name: ''
experiment_id: '869484762084459009'
lifecycle_stage: active
run_id: fc9989dbb9a9406eb14cb0db7b94ecc3
run_name: enthused-sloth-531
run_uuid: fc9989dbb9a9406eb14cb0db7b94ecc3
source_name: ''
source_type: 4
source_version: ''
start_time: 1748424136639
status: 3
tags: []
user_id: khrib
